name: Validate PR
on:
  pull_request:
    branches: [ master ]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-18.04
    env:
      DB_DATABASE: reports_integration_tests
      DB_USER: root
      DB_PASSWORD: root
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '5.6'
          root-password: 'root'
      - name: Test and build package
        run: ./mvnw -T 4 --no-transfer-progress -DskipDump=false -DskipConfig=false clean install
