name: Validate PR
on:
  pull_request:
    branches: [ master ]
jobs:
  build-package:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '8'
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build package
        run: ./mvnw --no-transfer-progress clean install -DskipTests
